Allow axis color to be changed
PennyQ/astro-vispy pull request #372
Opened 2022-07-20 16:33 UTC by Carifio24

While doing some work on the `glue-plotly` 3D scatter exporter, I noticed that it's not possible to change the axis color of an `AxesVisual3D` during runtime. This is due to the fact that the `color` attribute of a `vispy.visuals.line.LineVisual` is a property without a setter. To fix this, this PR changes the axis color to be updated using `set_data` instead.

2022-08-04 13:47 UTC, astrofrog requested changes
Looks good - as usual please add a changelog entry :)

2022-08-04 21:24 UTC, Carifio24 commented
@astrofrog Changeload entry has been added

2022-10-22 18:04 UTC, dhomeier commented
Sorry for the late reply @Carifio24 ; could you rebase this? – CI should be fixed now.

2022-10-22 21:00 UTC, Carifio24 commented
@dhomeier My commit added a 1.0.6 section to the changelog - should I reformat that to match the new style? Or just ditch the changelog commit? I don't want to muck up the auto-release action.

2022-10-22 21:10 UTC, dhomeier commented
You could simply ditch it, as there would be some merge conflicts anyway – otherwise the entry auto-generated from the title would just duplicate it; can still remove that at release time (or mark this PR `skip-changelog` so no new entry will be generated). But an entry left here in `CHANGES.md` will probably not be sorted nicely into the 'New Features' section.

2022-10-23 00:54 UTC, Carifio24 commented
@dhomeier I just ditched the changelog commit - that seems like the simpler option.

2022-11-16 20:23 UTC, Carifio24 commented
Are the CI failures here real, or something from an old CI run? It looks like the logs have expired.

2023-02-11 07:20 UTC, merged